/**
 * @author H.Nakazawa
 * @since  2025-09-25
 */
@isTest
public class naklab_TestExtendedCalloutUtility extends naklab_CalloutUtility {
    
    /**
     * @author H.Nakazawa
     * @since  2025-09-25
     * @param  endpoint
     * @param  method
     */
    public naklab_TestExtendedCalloutUtility( String endpoint , naklab_CalloutConfig.Enumeration method ){
        super( endpoint , method );
    }
    
}